/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvdstore;

import javax.swing.JOptionPane;

/**
 *
 * @author Yasser Khaled
 */
public class AdminSearchDvd extends javax.swing.JFrame {

    /**
     * Creates new form AdminSearchDvd
     */
    public static String DVDtitle;
    public AdminSearchDvd() 
    {
        initComponents();
    }
    
     public AdminSearchDvd(String s) {
        initComponents();
        this.setLocationRelativeTo(null);
        DVDtitle=s;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Delete = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoBox = new javax.swing.JTextArea();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        InfoBox.setEditable(false);
        InfoBox.setColumns(20);
        InfoBox.setRows(5);
        jScrollPane1.setViewportView(InfoBox);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Back)
                            .addGap(15, 15, 15))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Update)
                            .addGap(205, 205, 205)
                            .addComponent(Delete)
                            .addGap(31, 31, 31)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(Update))
                .addGap(18, 18, 18)
                .addComponent(Back)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        String name ,genre;
        int id,q,year;
        double price;
        id= Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the new id"));
        name=JOptionPane.showInputDialog(this, "Enter the new name");
        while(name==null || name.isEmpty())
        {
        JOptionPane.showMessageDialog(this, "You entered null value."); 
        name=JOptionPane.showInputDialog(this, "Enter the new name");
        }
        price= Double.parseDouble(JOptionPane.showInputDialog(this, "Enter the new price"));
        q= Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the new quantity"));
        genre= JOptionPane.showInputDialog(this, "Enter the new genre");
        year= Integer.parseInt(JOptionPane.showInputDialog(this, "Enter the new year"));
        
        if(Admin.updateDVD(DVDtitle, id, name, price, q, genre, year))
        {
            JOptionPane.showMessageDialog(this, "Successfully updated.");
            DVDtitle=name;
            displayInfoInBox();
        }
        else
            JOptionPane.showMessageDialog(this, "Update failed."); 
    }//GEN-LAST:event_UpdateActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        AdminMain am= new AdminMain();
            am.setVisible(true);
            am.setLocationRelativeTo(null);
            this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    
    /**
     * Loads Information Into the jTextArea
     */
    public static void displayInfoInBox()
    {
        DVD x = User.retrieveDVD(DVDtitle);
        String temp;
        if(x.getAvailability())
        temp="Available";
        else
        temp="Not Available";
        InfoBox.setText("ID: "+x.getID()+"\nName: "+x.getName()+"\nPrice: "+x.getPrice()+"\nGenre: "+x.getGenre()+"\nYear: "+x.getYear()+"\nAvailability: "+temp);
    }
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        if(Admin.deleteDVD(DVDtitle))
            JOptionPane.showMessageDialog(this, "Successfully Deleted");
        else
            JOptionPane.showMessageDialog(this, "Deleting Failed");
        AdminMain am= new AdminMain();
        am.setVisible(true);
        am.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSearchDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSearchDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSearchDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSearchDvd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSearchDvd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete;
    public static javax.swing.JTextArea InfoBox;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
