/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvdstore;

import static dvdstore.Login.loggedUserName;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author carleqladios
 */
public class BrowseOrRent extends javax.swing.JFrame {

    /**
     * Creates new form BrowseOrRent
     */
    public BrowseOrRent() {
        initComponents();
        dvdList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    displayInfo();
                }
            }
        });    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList <DVD> DVDList = User.browseDVD();
        final String [] DVDTitle = new String [DVDList.size()];
        for(int i=0;i<DVDList.size();i++)
        {
            DVDTitle[i]=DVDList.get(i).getName();
        }
        dvdList = new javax.swing.JList(DVDTitle);
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoArea = new javax.swing.JTextArea();
        Rent = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dvdList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = DVDTitle;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dvdList);

        InfoArea.setEditable(false);
        InfoArea.setColumns(20);
        InfoArea.setRows(5);
        jScrollPane2.setViewportView(InfoArea);

        Rent.setText("Rent");
        Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Rent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Loads Information Into the jTextArea
     */
    public static void displayInfo()
    {
        ArrayList <DVD> DVDList = User.browseDVD();
        DVD x = DVDList.get(dvdList.getSelectedIndex());
        String temp;
        if(x.getAvailability())
        temp="Available";
        else
        temp="Not Available";
        InfoArea.setText("ID: "+x.getID()+"\nName: "+x.getName()+"\nPrice: "+x.getPrice()+"\nQuantity: "+x.getQuantity()+"\nGenre: "+x.getGenre()+"\nYear: "+x.getYear()+"\nAvailability: "+temp);
    }
    private void RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentActionPerformed
        ArrayList <DVD>DVDList = User.browseDVD();
        DVD x = DVDList.get(dvdList.getSelectedIndex());
        Client c= Admin.retrieveClient(loggedUserName);
        for(int i=0;i<c.browseRented().size();i++)
        {
        if (x.getName().equals(c.browseRented().get(i).getDVDName()))
        {
             JOptionPane.showMessageDialog(this, "The DVD was already rented by you! ");
             return;
        }
        }
        String d = JOptionPane.showInputDialog(null, "Enter number of Days (Maximum of 7 days)") ; 
        int days = Integer.parseInt(d); 
        Date due = new Date();
        Calendar cal = Calendar.getInstance(); 
        cal.setTime(due); 
        cal.add(Calendar.DATE, days);
        due = cal.getTime();
        java.sql.Date temp = new java.sql.Date(due.getTime());
        
        double price = x.getPrice()*days ; 
        if (days <= 7 && days>0)
        {
        if (x.getAvailability()==true)
        {
           
            if(c.rentDVD(x.getID(), temp, price ))
            {
            JOptionPane.showMessageDialog(this, "The DVD was rented successfully! Rental Price is: "+price);
            displayInfo();
            }
            else
            JOptionPane.showMessageDialog(this, "Error");

        }
            else 
            JOptionPane.showMessageDialog(this, "Dvd is not Available ");
        }
            else 
        {
            JOptionPane.showMessageDialog(this, "Your number of days must not exceed 7 not be less than 1");
        }
    }//GEN-LAST:event_RentActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        UserMenu um= new UserMenu();
        um.setVisible(true);
        um.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrowseOrRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrowseOrRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrowseOrRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrowseOrRent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrowseOrRent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private static javax.swing.JTextArea InfoArea;
    private javax.swing.JButton Rent;
    private static javax.swing.JList dvdList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
