/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dvdstore;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author carleqladios
 */
public class returnDVD extends javax.swing.JFrame {

    /**
     * Creates new form returnDVD
     */
    public returnDVD() {
        initComponents();
        
        dvdList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    displayInfo();
                }
            }
        }); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        ReturnDVDBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        InfoArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        Client c = Admin.retrieveClient(Login.loggedUserName);
        ArrayList <Rentals> DVDList = c.browseRented();
        final String [] DVDTitle = new String [DVDList.size()];
        for(int i=0;i<DVDList.size();i++)
        {
            DVDTitle[i]=DVDList.get(i).getDVDName();
        }
        dvdList = new javax.swing.JList(DVDTitle);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        ReturnDVDBtn.setText("Return DVD");
        ReturnDVDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnDVDBtnActionPerformed(evt);
            }
        });

        InfoArea.setEditable(false);
        InfoArea.setColumns(20);
        InfoArea.setRows(5);
        jScrollPane2.setViewportView(InfoArea);

        dvdList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = DVDTitle;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dvdList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReturnDVDBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ReturnDVDBtn)
                .addGap(8, 8, 8)
                .addComponent(BackBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Loads Information Into the jTextArea
     */
    public static void displayInfo()
    {
        if (!dvdList.isSelectionEmpty())
        {
            Client c = Admin.retrieveClient(Login.loggedUserName);
            ArrayList <Rentals> DVDList = c.browseRented();
            Rentals x = DVDList.get(dvdList.getSelectedIndex());
            InfoArea.setText("DVD Title: "+x.getDVDName()+"\nDue Date: "+x.getDueDate()+"\nRental Price: "+x.getRentalPrice());
        }
        else
        {
            InfoArea.setText(null);
        }
    }
    
    /**
     * Rewrites the DVDList JList after returning DVD
     */
    public void refresh()
    {
        Client c = Admin.retrieveClient(Login.loggedUserName);
        ArrayList <Rentals> DVDList = c.browseRented();
        final String [] DVDTitle = new String [DVDList.size()];
        for(int i=0;i<DVDList.size();i++)
        {
            DVDTitle[i]=DVDList.get(i).getDVDName();
        }
        dvdList = new javax.swing.JList(DVDTitle);

        dvdList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = DVDTitle;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(dvdList);
    }
    
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        UserMenu um= new UserMenu();
        um.setVisible(true);
        um.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ReturnDVDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDVDBtnActionPerformed
        // TODO add your handling code here:
        Client u = Admin.retrieveClient(Login.loggedUserName);
        ArrayList <Rentals> rentalsList = u.browseRented();
        Rentals r = rentalsList.get(dvdList.getSelectedIndex());
        String dvdName=r.getDVDName();
        DVD rentedDVD = Admin.retrieveDVD(dvdName);
        int penalty = u.returnDVD(rentedDVD.getID());
        JOptionPane.showMessageDialog(null, "Thanks, Your penalty is: "+penalty);
        refresh();
        displayInfo();
    }//GEN-LAST:event_ReturnDVDBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(returnDVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(returnDVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(returnDVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(returnDVD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new returnDVD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private static javax.swing.JTextArea InfoArea;
    private javax.swing.JButton ReturnDVDBtn;
    private static javax.swing.JList dvdList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
